In [2]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

In [3]:
import random
from trailblazer4ml.causal_discovery.datasets.easydataset import EasyDataset

In [5]:
df = pd.read_csv("../trailblazer/trailblazer4ml/causal_inference/datasets/data/lalonde.csv")
covariates = ['age', 'educ', 'black', 'hispan', 'married', 'nodegree']
treat = ['treat']
outcomes = ['re78']
data = EasyDataset(df, covariates, treat, outcomes)

In [6]:
from trailblazer4ml.causal_discovery.estimators.PC_based import PC
out = PC(data)
out._get_adjacent_matrix()

Data size: 614
[[0 1 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 1]
 [0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


method  edge_start  edge_end  estimate_value
0      PC           0         1               1
1      PC           0         4               1
2      PC           1         3               1
3      PC           1         5               1
4      PC           1         7               1
5      PC           2         3               1
6      PC           2         6               1
7      PC           4         2               1
8      PC           4         6               1
9      PC           4         7               1
10     PC           5         6               1